import React from "react";
import Enzyme, { mount } from "enzyme";
import Adapter from "@wojtekmaj/enzyme-adapter-react-17";
Enzyme.configure({ adapter: new Adapter() });
import ProjectForm from "./ProjectForm";
import { render } from "@testing-library/react";
import ReactDOM from "react-dom";
import ReactTestUtils from "react-dom/test-utils";
import SubmitButton from "./FormFooter/SubmitButton";

it("form component can be mounted and form element is found", () => {
  const projectForm = mount(<ProjectForm />);

  expect(projectForm.find("form").length).toBe(1);
});

it("form can be submitted", () => {
  const handleSubmit = jest.fn();

  mount(<ProjectForm onSubmit={handleSubmit()} />);
  expect(handleSubmit).toHaveBeenCalledTimes(1);
});

it("form can be and is getting rendered", () => {
  const { getByTestId } = render(<ProjectForm />);

  expect(getByTestId("form-test")).toBeTruthy();
});

describe("ProjectForm", () => {
  it("form is being submitted when submit event fires while pressing submit button", () => {
    const callback = jest.fn();
    const wrapper = mount(<SubmitButton handleSubmit={callback} />);

    wrapper.find('[type="submit"]').at(0).simulate("click");
    expect(callback).toHaveBeenCalledTimes(1);
  });
});

it("as form starts rendering the input field is blank as it should be (anti spam robots technique)", () => {
  const wrapper = document.createElement("div");

  ReactDOM.render(<ProjectForm />, wrapper);

  const input = wrapper.querySelector(".name-input");

  expect(input.value).toEqual("");
});

it("testing that name input value can be controlled with onChange event and the value is being changed ", () => {
  const wrapper = document.createElement("div");
  ReactDOM.render(<ProjectForm />, wrapper);
  const input = wrapper.querySelector(".name-input");
  const form = wrapper.querySelector("form");

  ReactTestUtils.Simulate.change(input, { target: { value: "Test" } });
  ReactTestUtils.Simulate.submit(form);

  expect(input.value).toEqual("Test");
});

it("success message should not appear if submitting a blank form", () => {
  const wrapper = mount(<ProjectForm />);
  const form = wrapper.find("form");

  form.simulate("submit");
  expect(form.find(".success").exists()).toBeFalsy();
});

it("success message should no appear if only the name is added while submitting", () => {
  const wrapper = mount(<ProjectForm />);
  const form = wrapper.find("form");

  const input = form.find(".name-input");
  input.simulate("change", { target: { value: "Jhon Doe" } });

  form.simulate("submit");
  expect(form.find(".success").exists()).toBeFalsy();
});

it("Form adds projects correctly after entering a project name and pressing enter", () => {
  const wrapper = document.createElement("div");
  ReactDOM.render(<ProjectForm />, wrapper);
  const tagInput = wrapper.querySelector(".tag-input");

  ReactTestUtils.Simulate.change(tagInput, { target: { value: "Test" } });

  expect(tagInput.value).toEqual("Test");

  expect(wrapper.querySelector(".project-tag")).toBeFalsy();

  ReactTestUtils.Simulate.change(tagInput, { target: { value: "Test" } });
  ReactTestUtils.Simulate.keyDown(tagInput, { key: "Enter" });

  expect(wrapper.querySelector(".project-tag")).toBeTruthy();
});

it("Project detail components can be generated by clicking add icon", () => {
  const wrapper = document.createElement("div");
  ReactDOM.render(<ProjectForm />, wrapper);
  const addIcon = wrapper.querySelector(".add-icon");
  expect(addIcon).toBeTruthy();
  expect(wrapper.querySelector(".added-projects")).toBeFalsy();
  ReactTestUtils.Simulate.click(addIcon);
  expect(wrapper.querySelector(".added-projects")).toBeTruthy();
});

it("Form submits with success if corect form data is added, form data is valid and we can do what we want with it", () => {
  const wrapper = document.createElement("div");
  ReactDOM.render(<ProjectForm />, wrapper);
  const nameInput = wrapper.querySelector(".name-input");
  const tagInput = wrapper.querySelector(".tag-input");

  ReactTestUtils.Simulate.change(nameInput, { target: { value: "Jhon Doe" } });
  ReactTestUtils.Simulate.change(tagInput, { target: { value: "Project X" } });

  expect(nameInput.value).toEqual("Jhon Doe");
  expect(tagInput.value).toEqual("Project X");
  expect(wrapper.querySelector(".project-tag")).toBeFalsy();
  ReactTestUtils.Simulate.keyDown(tagInput, { key: "Enter" });
  expect(wrapper.querySelector(".project-tag")).toBeTruthy();
  const addIcon = wrapper.querySelector(".add-icon");
  expect(addIcon).toBeTruthy();
  expect(wrapper.querySelector(".added-projects")).toBeFalsy();
  ReactTestUtils.Simulate.click(addIcon);
  expect(wrapper.querySelector(".added-projects")).toBeTruthy();
  const selectProject = wrapper.querySelector(".project-select");
  expect(selectProject).toBeTruthy();
  ReactTestUtils.Simulate.change(selectProject, {
    target: { value: "Project X" },
  });
  const detailTextarea = wrapper.querySelector(".details-textarea");
  expect(detailTextarea).toBeTruthy();
  ReactTestUtils.Simulate.change(detailTextarea, {
    target: { value: "I have been project manager of this project and ..." },
  });
  expect(selectProject.value).toEqual("Project X");
  expect(detailTextarea.value).toEqual(
    "I have been project manager of this project and ..."
  );
  const durationUnits = wrapper.querySelector(".duration-select");
  expect(durationUnits).toBeTruthy();
  ReactTestUtils.Simulate.change(durationUnits, { target: { value: "years" } });
  expect(durationUnits.value).toEqual("years");
  expect(wrapper.querySelector(".success")).toBeFalsy();
  const durationInput = wrapper.querySelector(".duration-input");
  expect(durationInput).toBeTruthy();
  ReactTestUtils.Simulate.change(durationInput, { target: { value: "1" } });
  expect(durationInput.value).toEqual("1");

  const submitBtn = wrapper.querySelector(".submit-btn");
  ReactTestUtils.Simulate.click(submitBtn);

  //And the moment of truth :)
  expect(wrapper.querySelector(".success")).toBeTruthy();
});
